### ISSUE TITLE
npm install 最后出错

### ISSUE THREAD

**Issue by ccqiuqiu** [bodyno/universal-react-starter-kit#4]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):                         
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"
os":"win32","arch":"x64"})                                                                                                             
npm ERR! Windows_NT 10.0.15063                                                                                                         
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"                
npm ERR! node v6.10.1                                                                                                                  
npm ERR! npm  v3.10.10                                                                                                                 
npm ERR! path C:\Users\cc\Desktop\node.js\universal-react-starter-kit\node_modules\.staging\ajv-2dadfe81                               
npm ERR! code EPERM                                                                                                                    
npm ERR! errno -4048                                                                                                                   
npm ERR! syscall rename                                                                                                                

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\cc\Desktop\node.js\universal-react-starter-kit\node_modules\.staging\ajv-2dadfe81' -> 'C:\Users\cc\Desktop\node.js\universal-react-starter-kit\node_modules\ajv'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\cc\Desktop\node.js\universal-react-starter-kit\node_modules\.staging\ajv-2dadfe81' -> 'C:\Users\cc\Desktop\node.js\universal-react-starter-kit\node_modules\ajv'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\cc\Desktop\node.js\universal-react-starter-kit\node_modules\.staging\ajv-2dadfe81' -> 'C:\Users\cc\Desktop\node.js\universal-react-starter-kit\node_modules\ajv'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\cc\Desktop\node.js\universal-react-starter-kit\node_modules\.staging\ajv-2dadfe81' -> 'C:\Users\cc\Desktop\node.js\universal-react-starter-kit\node_modules\ajv'
npm ERR!     at Error (native) parent: 'react-redux-starter-kit' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cc\Desktop\node.js\universal-react-starter-kit\npm-debug.log

**Comment by bodyno** [comment]
换cnpm运行下
